# Generated by Django 4.0.2 on 2022-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
