# Generated by Django 4.0.2 on 2022-03-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cinema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='reviews.cinema'),
            preserve_default=False,
        ),
    ]
